# Generated by Django 3.2.18 on 2023-03-30 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_create', models.DateField(auto_now_add=True)),
                ('area_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fe_create', models.DateTimeField(auto_now_add=True)),
                ('fe_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MesaPartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.IntegerField()),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fe_create', models.DateTimeField(auto_now_add=True)),
                ('fe_update', models.DateTimeField(auto_now=True)),
                ('derivacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.derivacion')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documento')),
                ('estado_tramite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estadotramite')),
                ('mesa_partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mesapartes')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('remitente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.remitente')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_create', models.DateField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadorespuesta')),
                ('personal_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personalarea')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tramite')),
            ],
        ),
        migrations.AddField(
            model_name='remitente',
            name='tipo_remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente'),
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_create', models.DateField(auto_now_add=True)),
                ('personal_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personalarea')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('remitente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.remitente')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='mesapartes',
            name='documentos',
            field=models.ManyToManyField(through='core.Tramite', to='core.Documento'),
        ),
        migrations.AddField(
            model_name='mesapartes',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('remitente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.remitente')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfil'),
        ),
        migrations.AddField(
            model_name='documento',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.remitente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipodocumento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente'),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='personal_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personalarea'),
        ),
    ]
