# Generated by Django 3.2.18 on 2023-04-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='perfil',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.PROTECT, to='core.perfil'),
            preserve_default=False,
        ),
    ]
