# Generated by Django 3.2.18 on 2023-04-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230403_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='personanatural',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='remitente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='remitente',
            name='codigo_trabajador',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='remitente',
            name='correo',
            field=models.EmailField(default=int, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remitente',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='remitente',
            name='nombres',
            field=models.CharField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remitente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='remitente',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='remitente',
            name='telefono',
            field=models.CharField(default=int, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='PersonaNatural',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
        migrations.AddField(
            model_name='remitente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ciudad'),
        ),
        migrations.AddField(
            model_name='remitente',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
    ]
