# Generated by Django 3.2.18 on 2023-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230403_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadotramite',
            name='tramite_padre',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
