# Generated by Django 3.2.18 on 2023-04-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tramite_fecha_recepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivacion',
            name='personal_area',
        ),
        migrations.AddField(
            model_name='derivacion',
            name='mesa_partes',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.PROTECT, to='core.mesapartes'),
            preserve_default=False,
        ),
    ]
