# Generated by Django 3.2.18 on 2023-07-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230405_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_create', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.cargo'),
            preserve_default=False,
        ),
    ]
